# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mushroom' do
  use_frameworks!

  # Pods for mushroom
  pod "Alamofire"
  pod "SwiftyJSON"

  target 'mushroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mushroomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
